
package b4a.example3;

import java.io.IOException;
import anywheresoftware.b4a.BA;
import anywheresoftware.b4a.pc.PCBA;
import anywheresoftware.b4a.pc.RDebug;
import anywheresoftware.b4a.pc.RemoteObject;
import anywheresoftware.b4a.pc.RDebug.IRemote;
import anywheresoftware.b4a.pc.Debug;
import anywheresoftware.b4a.pc.B4XTypes.B4XClass;
import anywheresoftware.b4a.pc.B4XTypes.DeviceClass;

public class programveri implements IRemote{
	public static programveri mostCurrent;
	public static RemoteObject processBA;
    public static boolean processGlobalsRun;
    public static RemoteObject myClass;
    public static RemoteObject remoteMe;
	public programveri() {
		mostCurrent = this;
	}
    public RemoteObject getRemoteMe() {
        return remoteMe;    
    }
    
	public static void main (String[] args) throws Exception {
		new RDebug(args[0], Integer.parseInt(args[1]), Integer.parseInt(args[2]), args[3]);
		RDebug.INSTANCE.waitForTask();

	}
    static {
        anywheresoftware.b4a.pc.RapidSub.moduleToObject.put(new B4XClass("programveri"), "b4a.example3.programveri");
	}

public boolean isSingleton() {
		return true;
	}
     public static RemoteObject getObject() {
		return myClass;
	 }

	public RemoteObject activityBA;
	public RemoteObject _activity;
    private PCBA pcBA;

	public PCBA create(Object[] args) throws ClassNotFoundException{
		processBA = (RemoteObject) args[1];
		activityBA = (RemoteObject) args[2];
		_activity = (RemoteObject) args[3];
        anywheresoftware.b4a.keywords.Common.Density = (Float)args[4];
        remoteMe = (RemoteObject) args[5];
		pcBA = new PCBA(this, programveri.class);
        main_subs_0.initializeProcessGlobals();
		return pcBA;
	}
public static RemoteObject __c = RemoteObject.declareNull("anywheresoftware.b4a.keywords.Common");
public static RemoteObject _buttonok = RemoteObject.declareNull("anywheresoftware.b4a.objects.ButtonWrapper");
public static RemoteObject _scrollview1 = RemoteObject.declareNull("anywheresoftware.b4a.objects.ScrollViewWrapper");
public static RemoteObject _programid = RemoteObject.createImmutable(0);
public static RemoteObject _rs = RemoteObject.declareNull("anywheresoftware.b4a.sql.SQL.ResultSetWrapper");
public static RemoteObject _secilentarih = RemoteObject.createImmutable("");
public static RemoteObject _secilensaat = RemoteObject.createImmutable("");
public static RemoteObject _konimesafesi1 = RemoteObject.createImmutable(0f);
public static RemoteObject _konimesafesi2 = RemoteObject.createImmutable(0f);
public static RemoteObject _konimesafesi3 = RemoteObject.createImmutable(0f);
public static RemoteObject _konimesafesi4 = RemoteObject.createImmutable(0f);
public static RemoteObject _konimesafesi5 = RemoteObject.createImmutable(0f);
public static RemoteObject _konimesafesi6 = RemoteObject.createImmutable(0f);
public static RemoteObject _konimesafesi7 = RemoteObject.createImmutable(0f);
public static RemoteObject _konimesafesi8 = RemoteObject.createImmutable(0f);
public static RemoteObject _konimesafesi9 = RemoteObject.createImmutable(0f);
public static RemoteObject _konimesafesi10 = RemoteObject.createImmutable(0f);
public static RemoteObject _konimesafesi11 = RemoteObject.createImmutable(0f);
public static RemoteObject _konimesafesi12 = RemoteObject.createImmutable(0f);
public static RemoteObject _konimesafesi13 = RemoteObject.createImmutable(0f);
public static RemoteObject _konimesafesi14 = RemoteObject.createImmutable(0f);
public static RemoteObject _konimesafesi15 = RemoteObject.createImmutable(0f);
public static RemoteObject _konimesafesi16 = RemoteObject.createImmutable(0f);
public static RemoteObject _konimesafesi17 = RemoteObject.createImmutable(0f);
public static RemoteObject _konimesafesi18 = RemoteObject.createImmutable(0f);
public static RemoteObject _konimesafesi19 = RemoteObject.createImmutable(0f);
public static RemoteObject _konimesafesi20 = RemoteObject.createImmutable(0f);
public static RemoteObject _konimesafesi21 = RemoteObject.createImmutable(0f);
public static RemoteObject _konimesafesi22 = RemoteObject.createImmutable(0f);
public static RemoteObject _konimesafesi23 = RemoteObject.createImmutable(0f);
public static RemoteObject _konimesafesi24 = RemoteObject.createImmutable(0f);
public static RemoteObject _konimesafesi25 = RemoteObject.createImmutable(0f);
public static RemoteObject _hiz1 = RemoteObject.createImmutable(0f);
public static RemoteObject _hiz2 = RemoteObject.createImmutable(0f);
public static RemoteObject _hiz3 = RemoteObject.createImmutable(0f);
public static RemoteObject _hiz4 = RemoteObject.createImmutable(0f);
public static RemoteObject _hiz5 = RemoteObject.createImmutable(0f);
public static RemoteObject _hiz6 = RemoteObject.createImmutable(0f);
public static RemoteObject _hiz7 = RemoteObject.createImmutable(0f);
public static RemoteObject _hiz8 = RemoteObject.createImmutable(0f);
public static RemoteObject _hiz9 = RemoteObject.createImmutable(0f);
public static RemoteObject _hiz10 = RemoteObject.createImmutable(0f);
public static RemoteObject _hiz11 = RemoteObject.createImmutable(0f);
public static RemoteObject _hiz12 = RemoteObject.createImmutable(0f);
public static RemoteObject _hiz13 = RemoteObject.createImmutable(0f);
public static RemoteObject _hiz14 = RemoteObject.createImmutable(0f);
public static RemoteObject _hiz15 = RemoteObject.createImmutable(0f);
public static RemoteObject _hiz16 = RemoteObject.createImmutable(0f);
public static RemoteObject _hiz17 = RemoteObject.createImmutable(0f);
public static RemoteObject _hiz18 = RemoteObject.createImmutable(0f);
public static RemoteObject _hiz19 = RemoteObject.createImmutable(0f);
public static RemoteObject _hiz20 = RemoteObject.createImmutable(0f);
public static RemoteObject _hiz21 = RemoteObject.createImmutable(0f);
public static RemoteObject _hiz22 = RemoteObject.createImmutable(0f);
public static RemoteObject _hiz23 = RemoteObject.createImmutable(0f);
public static RemoteObject _hiz24 = RemoteObject.createImmutable(0f);
public static RemoteObject _hiz25 = RemoteObject.createImmutable(0f);
public static RemoteObject _dakika1 = RemoteObject.createImmutable(0);
public static RemoteObject _dakika2 = RemoteObject.createImmutable(0);
public static RemoteObject _dakika3 = RemoteObject.createImmutable(0);
public static RemoteObject _dakika4 = RemoteObject.createImmutable(0);
public static RemoteObject _dakika5 = RemoteObject.createImmutable(0);
public static RemoteObject _dakika6 = RemoteObject.createImmutable(0);
public static RemoteObject _dakika7 = RemoteObject.createImmutable(0);
public static RemoteObject _dakika8 = RemoteObject.createImmutable(0);
public static RemoteObject _dakika9 = RemoteObject.createImmutable(0);
public static RemoteObject _dakika10 = RemoteObject.createImmutable(0);
public static RemoteObject _dakika11 = RemoteObject.createImmutable(0);
public static RemoteObject _dakika12 = RemoteObject.createImmutable(0);
public static RemoteObject _dakika13 = RemoteObject.createImmutable(0);
public static RemoteObject _dakika14 = RemoteObject.createImmutable(0);
public static RemoteObject _dakika15 = RemoteObject.createImmutable(0);
public static RemoteObject _dakika16 = RemoteObject.createImmutable(0);
public static RemoteObject _dakika17 = RemoteObject.createImmutable(0);
public static RemoteObject _dakika18 = RemoteObject.createImmutable(0);
public static RemoteObject _dakika19 = RemoteObject.createImmutable(0);
public static RemoteObject _dakika20 = RemoteObject.createImmutable(0);
public static RemoteObject _dakika21 = RemoteObject.createImmutable(0);
public static RemoteObject _dakika22 = RemoteObject.createImmutable(0);
public static RemoteObject _dakika23 = RemoteObject.createImmutable(0);
public static RemoteObject _dakika24 = RemoteObject.createImmutable(0);
public static RemoteObject _dakika25 = RemoteObject.createImmutable(0);
public static RemoteObject _saniye1 = RemoteObject.createImmutable(0);
public static RemoteObject _saniye2 = RemoteObject.createImmutable(0);
public static RemoteObject _saniye3 = RemoteObject.createImmutable(0);
public static RemoteObject _saniye4 = RemoteObject.createImmutable(0);
public static RemoteObject _saniye5 = RemoteObject.createImmutable(0);
public static RemoteObject _saniye6 = RemoteObject.createImmutable(0);
public static RemoteObject _saniye7 = RemoteObject.createImmutable(0);
public static RemoteObject _saniye8 = RemoteObject.createImmutable(0);
public static RemoteObject _saniye9 = RemoteObject.createImmutable(0);
public static RemoteObject _saniye10 = RemoteObject.createImmutable(0);
public static RemoteObject _saniye11 = RemoteObject.createImmutable(0);
public static RemoteObject _saniye12 = RemoteObject.createImmutable(0);
public static RemoteObject _saniye13 = RemoteObject.createImmutable(0);
public static RemoteObject _saniye14 = RemoteObject.createImmutable(0);
public static RemoteObject _saniye15 = RemoteObject.createImmutable(0);
public static RemoteObject _saniye16 = RemoteObject.createImmutable(0);
public static RemoteObject _saniye17 = RemoteObject.createImmutable(0);
public static RemoteObject _saniye18 = RemoteObject.createImmutable(0);
public static RemoteObject _saniye19 = RemoteObject.createImmutable(0);
public static RemoteObject _saniye20 = RemoteObject.createImmutable(0);
public static RemoteObject _saniye21 = RemoteObject.createImmutable(0);
public static RemoteObject _saniye22 = RemoteObject.createImmutable(0);
public static RemoteObject _saniye23 = RemoteObject.createImmutable(0);
public static RemoteObject _saniye24 = RemoteObject.createImmutable(0);
public static RemoteObject _saniye25 = RemoteObject.createImmutable(0);
public static RemoteObject _labelseviyeismi1 = RemoteObject.declareNull("anywheresoftware.b4a.objects.LabelWrapper");
public static RemoteObject _labelseviyeismi2 = RemoteObject.declareNull("anywheresoftware.b4a.objects.LabelWrapper");
public static RemoteObject _labelseviyeismi3 = RemoteObject.declareNull("anywheresoftware.b4a.objects.LabelWrapper");
public static RemoteObject _labelseviyeismi4 = RemoteObject.declareNull("anywheresoftware.b4a.objects.LabelWrapper");
public static RemoteObject _labelseviyeismi5 = RemoteObject.declareNull("anywheresoftware.b4a.objects.LabelWrapper");
public static RemoteObject _labelseviyeismi6 = RemoteObject.declareNull("anywheresoftware.b4a.objects.LabelWrapper");
public static RemoteObject _labelseviyeismi7 = RemoteObject.declareNull("anywheresoftware.b4a.objects.LabelWrapper");
public static RemoteObject _labelseviyeismi8 = RemoteObject.declareNull("anywheresoftware.b4a.objects.LabelWrapper");
public static RemoteObject _labelseviyeismi9 = RemoteObject.declareNull("anywheresoftware.b4a.objects.LabelWrapper");
public static RemoteObject _labelseviyeismi10 = RemoteObject.declareNull("anywheresoftware.b4a.objects.LabelWrapper");
public static RemoteObject _labelseviyeismi11 = RemoteObject.declareNull("anywheresoftware.b4a.objects.LabelWrapper");
public static RemoteObject _labelseviyeismi12 = RemoteObject.declareNull("anywheresoftware.b4a.objects.LabelWrapper");
public static RemoteObject _labelseviyeismi13 = RemoteObject.declareNull("anywheresoftware.b4a.objects.LabelWrapper");
public static RemoteObject _labelseviyeismi14 = RemoteObject.declareNull("anywheresoftware.b4a.objects.LabelWrapper");
public static RemoteObject _labelseviyeismi15 = RemoteObject.declareNull("anywheresoftware.b4a.objects.LabelWrapper");
public static RemoteObject _labelseviyeismi16 = RemoteObject.declareNull("anywheresoftware.b4a.objects.LabelWrapper");
public static RemoteObject _labelseviyeismi17 = RemoteObject.declareNull("anywheresoftware.b4a.objects.LabelWrapper");
public static RemoteObject _labelseviyeismi18 = RemoteObject.declareNull("anywheresoftware.b4a.objects.LabelWrapper");
public static RemoteObject _labelseviyeismi19 = RemoteObject.declareNull("anywheresoftware.b4a.objects.LabelWrapper");
public static RemoteObject _labelseviyeismi20 = RemoteObject.declareNull("anywheresoftware.b4a.objects.LabelWrapper");
public static RemoteObject _labelseviyeismi21 = RemoteObject.declareNull("anywheresoftware.b4a.objects.LabelWrapper");
public static RemoteObject _labelseviyeismi22 = RemoteObject.declareNull("anywheresoftware.b4a.objects.LabelWrapper");
public static RemoteObject _labelseviyeismi23 = RemoteObject.declareNull("anywheresoftware.b4a.objects.LabelWrapper");
public static RemoteObject _labelseviyeismi24 = RemoteObject.declareNull("anywheresoftware.b4a.objects.LabelWrapper");
public static RemoteObject _labelseviyeismi25 = RemoteObject.declareNull("anywheresoftware.b4a.objects.LabelWrapper");
public static RemoteObject _labelhiz1 = RemoteObject.declareNull("anywheresoftware.b4a.objects.LabelWrapper");
public static RemoteObject _labelhiz2 = RemoteObject.declareNull("anywheresoftware.b4a.objects.LabelWrapper");
public static RemoteObject _labelhiz3 = RemoteObject.declareNull("anywheresoftware.b4a.objects.LabelWrapper");
public static RemoteObject _labelhiz4 = RemoteObject.declareNull("anywheresoftware.b4a.objects.LabelWrapper");
public static RemoteObject _labelhiz5 = RemoteObject.declareNull("anywheresoftware.b4a.objects.LabelWrapper");
public static RemoteObject _labelhiz6 = RemoteObject.declareNull("anywheresoftware.b4a.objects.LabelWrapper");
public static RemoteObject _labelhiz7 = RemoteObject.declareNull("anywheresoftware.b4a.objects.LabelWrapper");
public static RemoteObject _labelhiz8 = RemoteObject.declareNull("anywheresoftware.b4a.objects.LabelWrapper");
public static RemoteObject _labelhiz9 = RemoteObject.declareNull("anywheresoftware.b4a.objects.LabelWrapper");
public static RemoteObject _labelhiz10 = RemoteObject.declareNull("anywheresoftware.b4a.objects.LabelWrapper");
public static RemoteObject _labelhiz11 = RemoteObject.declareNull("anywheresoftware.b4a.objects.LabelWrapper");
public static RemoteObject _labelhiz12 = RemoteObject.declareNull("anywheresoftware.b4a.objects.LabelWrapper");
public static RemoteObject _labelhiz13 = RemoteObject.declareNull("anywheresoftware.b4a.objects.LabelWrapper");
public static RemoteObject _labelhiz14 = RemoteObject.declareNull("anywheresoftware.b4a.objects.LabelWrapper");
public static RemoteObject _labelhiz15 = RemoteObject.declareNull("anywheresoftware.b4a.objects.LabelWrapper");
public static RemoteObject _labelhiz16 = RemoteObject.declareNull("anywheresoftware.b4a.objects.LabelWrapper");
public static RemoteObject _labelhiz17 = RemoteObject.declareNull("anywheresoftware.b4a.objects.LabelWrapper");
public static RemoteObject _labelhiz18 = RemoteObject.declareNull("anywheresoftware.b4a.objects.LabelWrapper");
public static RemoteObject _labelhiz19 = RemoteObject.declareNull("anywheresoftware.b4a.objects.LabelWrapper");
public static RemoteObject _labelhiz20 = RemoteObject.declareNull("anywheresoftware.b4a.objects.LabelWrapper");
public static RemoteObject _labelhiz21 = RemoteObject.declareNull("anywheresoftware.b4a.objects.LabelWrapper");
public static RemoteObject _labelhiz22 = RemoteObject.declareNull("anywheresoftware.b4a.objects.LabelWrapper");
public static RemoteObject _labelhiz23 = RemoteObject.declareNull("anywheresoftware.b4a.objects.LabelWrapper");
public static RemoteObject _labelhiz24 = RemoteObject.declareNull("anywheresoftware.b4a.objects.LabelWrapper");
public static RemoteObject _labelhiz25 = RemoteObject.declareNull("anywheresoftware.b4a.objects.LabelWrapper");
public static RemoteObject _labeldakika1 = RemoteObject.declareNull("anywheresoftware.b4a.objects.LabelWrapper");
public static RemoteObject _labeldakika2 = RemoteObject.declareNull("anywheresoftware.b4a.objects.LabelWrapper");
public static RemoteObject _labeldakika3 = RemoteObject.declareNull("anywheresoftware.b4a.objects.LabelWrapper");
public static RemoteObject _labeldakika4 = RemoteObject.declareNull("anywheresoftware.b4a.objects.LabelWrapper");
public static RemoteObject _labeldakika5 = RemoteObject.declareNull("anywheresoftware.b4a.objects.LabelWrapper");
public static RemoteObject _labeldakika6 = RemoteObject.declareNull("anywheresoftware.b4a.objects.LabelWrapper");
public static RemoteObject _labeldakika7 = RemoteObject.declareNull("anywheresoftware.b4a.objects.LabelWrapper");
public static RemoteObject _labeldakika8 = RemoteObject.declareNull("anywheresoftware.b4a.objects.LabelWrapper");
public static RemoteObject _labeldakika9 = RemoteObject.declareNull("anywheresoftware.b4a.objects.LabelWrapper");
public static RemoteObject _labeldakika10 = RemoteObject.declareNull("anywheresoftware.b4a.objects.LabelWrapper");
public static RemoteObject _labeldakika11 = RemoteObject.declareNull("anywheresoftware.b4a.objects.LabelWrapper");
public static RemoteObject _labeldakika12 = RemoteObject.declareNull("anywheresoftware.b4a.objects.LabelWrapper");
public static RemoteObject _labeldakika13 = RemoteObject.declareNull("anywheresoftware.b4a.objects.LabelWrapper");
public static RemoteObject _labeldakika14 = RemoteObject.declareNull("anywheresoftware.b4a.objects.LabelWrapper");
public static RemoteObject _labeldakika15 = RemoteObject.declareNull("anywheresoftware.b4a.objects.LabelWrapper");
public static RemoteObject _labeldakika16 = RemoteObject.declareNull("anywheresoftware.b4a.objects.LabelWrapper");
public static RemoteObject _labeldakika17 = RemoteObject.declareNull("anywheresoftware.b4a.objects.LabelWrapper");
public static RemoteObject _labeldakika18 = RemoteObject.declareNull("anywheresoftware.b4a.objects.LabelWrapper");
public static RemoteObject _labeldakika19 = RemoteObject.declareNull("anywheresoftware.b4a.objects.LabelWrapper");
public static RemoteObject _labeldakika20 = RemoteObject.declareNull("anywheresoftware.b4a.objects.LabelWrapper");
public static RemoteObject _labeldakika21 = RemoteObject.declareNull("anywheresoftware.b4a.objects.LabelWrapper");
public static RemoteObject _labeldakika22 = RemoteObject.declareNull("anywheresoftware.b4a.objects.LabelWrapper");
public static RemoteObject _labeldakika23 = RemoteObject.declareNull("anywheresoftware.b4a.objects.LabelWrapper");
public static RemoteObject _labeldakika24 = RemoteObject.declareNull("anywheresoftware.b4a.objects.LabelWrapper");
public static RemoteObject _labeldakika25 = RemoteObject.declareNull("anywheresoftware.b4a.objects.LabelWrapper");
public static RemoteObject _labelsaniye1 = RemoteObject.declareNull("anywheresoftware.b4a.objects.LabelWrapper");
public static RemoteObject _labelsaniye2 = RemoteObject.declareNull("anywheresoftware.b4a.objects.LabelWrapper");
public static RemoteObject _labelsaniye3 = RemoteObject.declareNull("anywheresoftware.b4a.objects.LabelWrapper");
public static RemoteObject _labelsaniye4 = RemoteObject.declareNull("anywheresoftware.b4a.objects.LabelWrapper");
public static RemoteObject _labelsaniye5 = RemoteObject.declareNull("anywheresoftware.b4a.objects.LabelWrapper");
public static RemoteObject _labelsaniye6 = RemoteObject.declareNull("anywheresoftware.b4a.objects.LabelWrapper");
public static RemoteObject _labelsaniye7 = RemoteObject.declareNull("anywheresoftware.b4a.objects.LabelWrapper");
public static RemoteObject _labelsaniye8 = RemoteObject.declareNull("anywheresoftware.b4a.objects.LabelWrapper");
public static RemoteObject _labelsaniye9 = RemoteObject.declareNull("anywheresoftware.b4a.objects.LabelWrapper");
public static RemoteObject _labelsaniye10 = RemoteObject.declareNull("anywheresoftware.b4a.objects.LabelWrapper");
public static RemoteObject _labelsaniye11 = RemoteObject.declareNull("anywheresoftware.b4a.objects.LabelWrapper");
public static RemoteObject _labelsaniye12 = RemoteObject.declareNull("anywheresoftware.b4a.objects.LabelWrapper");
public static RemoteObject _labelsaniye13 = RemoteObject.declareNull("anywheresoftware.b4a.objects.LabelWrapper");
public static RemoteObject _labelsaniye14 = RemoteObject.declareNull("anywheresoftware.b4a.objects.LabelWrapper");
public static RemoteObject _labelsaniye15 = RemoteObject.declareNull("anywheresoftware.b4a.objects.LabelWrapper");
public static RemoteObject _labelsaniye16 = RemoteObject.declareNull("anywheresoftware.b4a.objects.LabelWrapper");
public static RemoteObject _labelsaniye17 = RemoteObject.declareNull("anywheresoftware.b4a.objects.LabelWrapper");
public static RemoteObject _labelsaniye18 = RemoteObject.declareNull("anywheresoftware.b4a.objects.LabelWrapper");
public static RemoteObject _labelsaniye19 = RemoteObject.declareNull("anywheresoftware.b4a.objects.LabelWrapper");
public static RemoteObject _labelsaniye20 = RemoteObject.declareNull("anywheresoftware.b4a.objects.LabelWrapper");
public static RemoteObject _labelsaniye21 = RemoteObject.declareNull("anywheresoftware.b4a.objects.LabelWrapper");
public static RemoteObject _labelsaniye22 = RemoteObject.declareNull("anywheresoftware.b4a.objects.LabelWrapper");
public static RemoteObject _labelsaniye23 = RemoteObject.declareNull("anywheresoftware.b4a.objects.LabelWrapper");
public static RemoteObject _labelsaniye24 = RemoteObject.declareNull("anywheresoftware.b4a.objects.LabelWrapper");
public static RemoteObject _labelsaniye25 = RemoteObject.declareNull("anywheresoftware.b4a.objects.LabelWrapper");
public static RemoteObject _labelkonimesafesi1 = RemoteObject.declareNull("anywheresoftware.b4a.objects.LabelWrapper");
public static RemoteObject _labelkonimesafesi2 = RemoteObject.declareNull("anywheresoftware.b4a.objects.LabelWrapper");
public static RemoteObject _labelkonimesafesi3 = RemoteObject.declareNull("anywheresoftware.b4a.objects.LabelWrapper");
public static RemoteObject _labelkonimesafesi4 = RemoteObject.declareNull("anywheresoftware.b4a.objects.LabelWrapper");
public static RemoteObject _labelkonimesafesi5 = RemoteObject.declareNull("anywheresoftware.b4a.objects.LabelWrapper");
public static RemoteObject _labelkonimesafesi6 = RemoteObject.declareNull("anywheresoftware.b4a.objects.LabelWrapper");
public static RemoteObject _labelkonimesafesi7 = RemoteObject.declareNull("anywheresoftware.b4a.objects.LabelWrapper");
public static RemoteObject _labelkonimesafesi8 = RemoteObject.declareNull("anywheresoftware.b4a.objects.LabelWrapper");
public static RemoteObject _labelkonimesafesi9 = RemoteObject.declareNull("anywheresoftware.b4a.objects.LabelWrapper");
public static RemoteObject _labelkonimesafesi10 = RemoteObject.declareNull("anywheresoftware.b4a.objects.LabelWrapper");
public static RemoteObject _labelkonimesafesi11 = RemoteObject.declareNull("anywheresoftware.b4a.objects.LabelWrapper");
public static RemoteObject _labelkonimesafesi12 = RemoteObject.declareNull("anywheresoftware.b4a.objects.LabelWrapper");
public static RemoteObject _labelkonimesafesi13 = RemoteObject.declareNull("anywheresoftware.b4a.objects.LabelWrapper");
public static RemoteObject _labelkonimesafesi14 = RemoteObject.declareNull("anywheresoftware.b4a.objects.LabelWrapper");
public static RemoteObject _labelkonimesafesi15 = RemoteObject.declareNull("anywheresoftware.b4a.objects.LabelWrapper");
public static RemoteObject _labelkonimesafesi16 = RemoteObject.declareNull("anywheresoftware.b4a.objects.LabelWrapper");
public static RemoteObject _labelkonimesafesi17 = RemoteObject.declareNull("anywheresoftware.b4a.objects.LabelWrapper");
public static RemoteObject _labelkonimesafesi18 = RemoteObject.declareNull("anywheresoftware.b4a.objects.LabelWrapper");
public static RemoteObject _labelkonimesafesi19 = RemoteObject.declareNull("anywheresoftware.b4a.objects.LabelWrapper");
public static RemoteObject _labelkonimesafesi20 = RemoteObject.declareNull("anywheresoftware.b4a.objects.LabelWrapper");
public static RemoteObject _labelkonimesafesi21 = RemoteObject.declareNull("anywheresoftware.b4a.objects.LabelWrapper");
public static RemoteObject _labelkonimesafesi22 = RemoteObject.declareNull("anywheresoftware.b4a.objects.LabelWrapper");
public static RemoteObject _labelkonimesafesi23 = RemoteObject.declareNull("anywheresoftware.b4a.objects.LabelWrapper");
public static RemoteObject _labelkonimesafesi24 = RemoteObject.declareNull("anywheresoftware.b4a.objects.LabelWrapper");
public static RemoteObject _labelkonimesafesi25 = RemoteObject.declareNull("anywheresoftware.b4a.objects.LabelWrapper");
public static RemoteObject _edittextkonimesafesi1 = RemoteObject.declareNull("anywheresoftware.b4a.objects.EditTextWrapper");
public static RemoteObject _edittextkonimesafesi2 = RemoteObject.declareNull("anywheresoftware.b4a.objects.EditTextWrapper");
public static RemoteObject _edittextkonimesafesi3 = RemoteObject.declareNull("anywheresoftware.b4a.objects.EditTextWrapper");
public static RemoteObject _edittextkonimesafesi4 = RemoteObject.declareNull("anywheresoftware.b4a.objects.EditTextWrapper");
public static RemoteObject _edittextkonimesafesi5 = RemoteObject.declareNull("anywheresoftware.b4a.objects.EditTextWrapper");
public static RemoteObject _edittextkonimesafesi6 = RemoteObject.declareNull("anywheresoftware.b4a.objects.EditTextWrapper");
public static RemoteObject _edittextkonimesafesi7 = RemoteObject.declareNull("anywheresoftware.b4a.objects.EditTextWrapper");
public static RemoteObject _edittextkonimesafesi8 = RemoteObject.declareNull("anywheresoftware.b4a.objects.EditTextWrapper");
public static RemoteObject _edittextkonimesafesi9 = RemoteObject.declareNull("anywheresoftware.b4a.objects.EditTextWrapper");
public static RemoteObject _edittextkonimesafesi10 = RemoteObject.declareNull("anywheresoftware.b4a.objects.EditTextWrapper");
public static RemoteObject _edittextkonimesafesi11 = RemoteObject.declareNull("anywheresoftware.b4a.objects.EditTextWrapper");
public static RemoteObject _edittextkonimesafesi12 = RemoteObject.declareNull("anywheresoftware.b4a.objects.EditTextWrapper");
public static RemoteObject _edittextkonimesafesi13 = RemoteObject.declareNull("anywheresoftware.b4a.objects.EditTextWrapper");
public static RemoteObject _edittextkonimesafesi14 = RemoteObject.declareNull("anywheresoftware.b4a.objects.EditTextWrapper");
public static RemoteObject _edittextkonimesafesi15 = RemoteObject.declareNull("anywheresoftware.b4a.objects.EditTextWrapper");
public static RemoteObject _edittextkonimesafesi16 = RemoteObject.declareNull("anywheresoftware.b4a.objects.EditTextWrapper");
public static RemoteObject _edittextkonimesafesi17 = RemoteObject.declareNull("anywheresoftware.b4a.objects.EditTextWrapper");
public static RemoteObject _edittextkonimesafesi18 = RemoteObject.declareNull("anywheresoftware.b4a.objects.EditTextWrapper");
public static RemoteObject _edittextkonimesafesi19 = RemoteObject.declareNull("anywheresoftware.b4a.objects.EditTextWrapper");
public static RemoteObject _edittextkonimesafesi20 = RemoteObject.declareNull("anywheresoftware.b4a.objects.EditTextWrapper");
public static RemoteObject _edittextkonimesafesi21 = RemoteObject.declareNull("anywheresoftware.b4a.objects.EditTextWrapper");
public static RemoteObject _edittextkonimesafesi22 = RemoteObject.declareNull("anywheresoftware.b4a.objects.EditTextWrapper");
public static RemoteObject _edittextkonimesafesi23 = RemoteObject.declareNull("anywheresoftware.b4a.objects.EditTextWrapper");
public static RemoteObject _edittextkonimesafesi24 = RemoteObject.declareNull("anywheresoftware.b4a.objects.EditTextWrapper");
public static RemoteObject _edittextkonimesafesi25 = RemoteObject.declareNull("anywheresoftware.b4a.objects.EditTextWrapper");
public static RemoteObject _edittexthiz1 = RemoteObject.declareNull("anywheresoftware.b4a.objects.EditTextWrapper");
public static RemoteObject _edittexthiz2 = RemoteObject.declareNull("anywheresoftware.b4a.objects.EditTextWrapper");
public static RemoteObject _edittexthiz3 = RemoteObject.declareNull("anywheresoftware.b4a.objects.EditTextWrapper");
public static RemoteObject _edittexthiz4 = RemoteObject.declareNull("anywheresoftware.b4a.objects.EditTextWrapper");
public static RemoteObject _edittexthiz5 = RemoteObject.declareNull("anywheresoftware.b4a.objects.EditTextWrapper");
public static RemoteObject _edittexthiz6 = RemoteObject.declareNull("anywheresoftware.b4a.objects.EditTextWrapper");
public static RemoteObject _edittexthiz7 = RemoteObject.declareNull("anywheresoftware.b4a.objects.EditTextWrapper");
public static RemoteObject _edittexthiz8 = RemoteObject.declareNull("anywheresoftware.b4a.objects.EditTextWrapper");
public static RemoteObject _edittexthiz9 = RemoteObject.declareNull("anywheresoftware.b4a.objects.EditTextWrapper");
public static RemoteObject _edittexthiz10 = RemoteObject.declareNull("anywheresoftware.b4a.objects.EditTextWrapper");
public static RemoteObject _edittexthiz11 = RemoteObject.declareNull("anywheresoftware.b4a.objects.EditTextWrapper");
public static RemoteObject _edittexthiz12 = RemoteObject.declareNull("anywheresoftware.b4a.objects.EditTextWrapper");
public static RemoteObject _edittexthiz13 = RemoteObject.declareNull("anywheresoftware.b4a.objects.EditTextWrapper");
public static RemoteObject _edittexthiz14 = RemoteObject.declareNull("anywheresoftware.b4a.objects.EditTextWrapper");
public static RemoteObject _edittexthiz15 = RemoteObject.declareNull("anywheresoftware.b4a.objects.EditTextWrapper");
public static RemoteObject _edittexthiz16 = RemoteObject.declareNull("anywheresoftware.b4a.objects.EditTextWrapper");
public static RemoteObject _edittexthiz17 = RemoteObject.declareNull("anywheresoftware.b4a.objects.EditTextWrapper");
public static RemoteObject _edittexthiz18 = RemoteObject.declareNull("anywheresoftware.b4a.objects.EditTextWrapper");
public static RemoteObject _edittexthiz19 = RemoteObject.declareNull("anywheresoftware.b4a.objects.EditTextWrapper");
public static RemoteObject _edittexthiz20 = RemoteObject.declareNull("anywheresoftware.b4a.objects.EditTextWrapper");
public static RemoteObject _edittexthiz21 = RemoteObject.declareNull("anywheresoftware.b4a.objects.EditTextWrapper");
public static RemoteObject _edittexthiz22 = RemoteObject.declareNull("anywheresoftware.b4a.objects.EditTextWrapper");
public static RemoteObject _edittexthiz23 = RemoteObject.declareNull("anywheresoftware.b4a.objects.EditTextWrapper");
public static RemoteObject _edittexthiz24 = RemoteObject.declareNull("anywheresoftware.b4a.objects.EditTextWrapper");
public static RemoteObject _edittexthiz25 = RemoteObject.declareNull("anywheresoftware.b4a.objects.EditTextWrapper");
public static RemoteObject _edittextdakika1 = RemoteObject.declareNull("anywheresoftware.b4a.objects.EditTextWrapper");
public static RemoteObject _edittextdakika2 = RemoteObject.declareNull("anywheresoftware.b4a.objects.EditTextWrapper");
public static RemoteObject _edittextdakika3 = RemoteObject.declareNull("anywheresoftware.b4a.objects.EditTextWrapper");
public static RemoteObject _edittextdakika4 = RemoteObject.declareNull("anywheresoftware.b4a.objects.EditTextWrapper");
public static RemoteObject _edittextdakika5 = RemoteObject.declareNull("anywheresoftware.b4a.objects.EditTextWrapper");
public static RemoteObject _edittextdakika6 = RemoteObject.declareNull("anywheresoftware.b4a.objects.EditTextWrapper");
public static RemoteObject _edittextdakika7 = RemoteObject.declareNull("anywheresoftware.b4a.objects.EditTextWrapper");
public static RemoteObject _edittextdakika8 = RemoteObject.declareNull("anywheresoftware.b4a.objects.EditTextWrapper");
public static RemoteObject _edittextdakika9 = RemoteObject.declareNull("anywheresoftware.b4a.objects.EditTextWrapper");
public static RemoteObject _edittextdakika10 = RemoteObject.declareNull("anywheresoftware.b4a.objects.EditTextWrapper");
public static RemoteObject _edittextdakika11 = RemoteObject.declareNull("anywheresoftware.b4a.objects.EditTextWrapper");
public static RemoteObject _edittextdakika12 = RemoteObject.declareNull("anywheresoftware.b4a.objects.EditTextWrapper");
public static RemoteObject _edittextdakika13 = RemoteObject.declareNull("anywheresoftware.b4a.objects.EditTextWrapper");
public static RemoteObject _edittextdakika14 = RemoteObject.declareNull("anywheresoftware.b4a.objects.EditTextWrapper");
public static RemoteObject _edittextdakika15 = RemoteObject.declareNull("anywheresoftware.b4a.objects.EditTextWrapper");
public static RemoteObject _edittextdakika16 = RemoteObject.declareNull("anywheresoftware.b4a.objects.EditTextWrapper");
public static RemoteObject _edittextdakika17 = RemoteObject.declareNull("anywheresoftware.b4a.objects.EditTextWrapper");
public static RemoteObject _edittextdakika18 = RemoteObject.declareNull("anywheresoftware.b4a.objects.EditTextWrapper");
public static RemoteObject _edittextdakika19 = RemoteObject.declareNull("anywheresoftware.b4a.objects.EditTextWrapper");
public static RemoteObject _edittextdakika20 = RemoteObject.declareNull("anywheresoftware.b4a.objects.EditTextWrapper");
public static RemoteObject _edittextdakika21 = RemoteObject.declareNull("anywheresoftware.b4a.objects.EditTextWrapper");
public static RemoteObject _edittextdakika22 = RemoteObject.declareNull("anywheresoftware.b4a.objects.EditTextWrapper");
public static RemoteObject _edittextdakika23 = RemoteObject.declareNull("anywheresoftware.b4a.objects.EditTextWrapper");
public static RemoteObject _edittextdakika24 = RemoteObject.declareNull("anywheresoftware.b4a.objects.EditTextWrapper");
public static RemoteObject _edittextdakika25 = RemoteObject.declareNull("anywheresoftware.b4a.objects.EditTextWrapper");
public static RemoteObject _edittextsaniye1 = RemoteObject.declareNull("anywheresoftware.b4a.objects.EditTextWrapper");
public static RemoteObject _edittextsaniye2 = RemoteObject.declareNull("anywheresoftware.b4a.objects.EditTextWrapper");
public static RemoteObject _edittextsaniye3 = RemoteObject.declareNull("anywheresoftware.b4a.objects.EditTextWrapper");
public static RemoteObject _edittextsaniye4 = RemoteObject.declareNull("anywheresoftware.b4a.objects.EditTextWrapper");
public static RemoteObject _edittextsaniye5 = RemoteObject.declareNull("anywheresoftware.b4a.objects.EditTextWrapper");
public static RemoteObject _edittextsaniye6 = RemoteObject.declareNull("anywheresoftware.b4a.objects.EditTextWrapper");
public static RemoteObject _edittextsaniye7 = RemoteObject.declareNull("anywheresoftware.b4a.objects.EditTextWrapper");
public static RemoteObject _edittextsaniye8 = RemoteObject.declareNull("anywheresoftware.b4a.objects.EditTextWrapper");
public static RemoteObject _edittextsaniye9 = RemoteObject.declareNull("anywheresoftware.b4a.objects.EditTextWrapper");
public static RemoteObject _edittextsaniye10 = RemoteObject.declareNull("anywheresoftware.b4a.objects.EditTextWrapper");
public static RemoteObject _edittextsaniye11 = RemoteObject.declareNull("anywheresoftware.b4a.objects.EditTextWrapper");
public static RemoteObject _edittextsaniye12 = RemoteObject.declareNull("anywheresoftware.b4a.objects.EditTextWrapper");
public static RemoteObject _edittextsaniye13 = RemoteObject.declareNull("anywheresoftware.b4a.objects.EditTextWrapper");
public static RemoteObject _edittextsaniye14 = RemoteObject.declareNull("anywheresoftware.b4a.objects.EditTextWrapper");
public static RemoteObject _edittextsaniye15 = RemoteObject.declareNull("anywheresoftware.b4a.objects.EditTextWrapper");
public static RemoteObject _edittextsaniye16 = RemoteObject.declareNull("anywheresoftware.b4a.objects.EditTextWrapper");
public static RemoteObject _edittextsaniye17 = RemoteObject.declareNull("anywheresoftware.b4a.objects.EditTextWrapper");
public static RemoteObject _edittextsaniye18 = RemoteObject.declareNull("anywheresoftware.b4a.objects.EditTextWrapper");
public static RemoteObject _edittextsaniye19 = RemoteObject.declareNull("anywheresoftware.b4a.objects.EditTextWrapper");
public static RemoteObject _edittextsaniye20 = RemoteObject.declareNull("anywheresoftware.b4a.objects.EditTextWrapper");
public static RemoteObject _edittextsaniye21 = RemoteObject.declareNull("anywheresoftware.b4a.objects.EditTextWrapper");
public static RemoteObject _edittextsaniye22 = RemoteObject.declareNull("anywheresoftware.b4a.objects.EditTextWrapper");
public static RemoteObject _edittextsaniye23 = RemoteObject.declareNull("anywheresoftware.b4a.objects.EditTextWrapper");
public static RemoteObject _edittextsaniye24 = RemoteObject.declareNull("anywheresoftware.b4a.objects.EditTextWrapper");
public static RemoteObject _edittextsaniye25 = RemoteObject.declareNull("anywheresoftware.b4a.objects.EditTextWrapper");
public static RemoteObject _panel1 = RemoteObject.declareNull("anywheresoftware.b4a.objects.PanelWrapper");
public static RemoteObject _panel2 = RemoteObject.declareNull("anywheresoftware.b4a.objects.PanelWrapper");
public static RemoteObject _panel3 = RemoteObject.declareNull("anywheresoftware.b4a.objects.PanelWrapper");
public static RemoteObject _panel4 = RemoteObject.declareNull("anywheresoftware.b4a.objects.PanelWrapper");
public static RemoteObject _panel5 = RemoteObject.declareNull("anywheresoftware.b4a.objects.PanelWrapper");
public static RemoteObject _panel6 = RemoteObject.declareNull("anywheresoftware.b4a.objects.PanelWrapper");
public static RemoteObject _panel7 = RemoteObject.declareNull("anywheresoftware.b4a.objects.PanelWrapper");
public static RemoteObject _panel8 = RemoteObject.declareNull("anywheresoftware.b4a.objects.PanelWrapper");
public static RemoteObject _panel9 = RemoteObject.declareNull("anywheresoftware.b4a.objects.PanelWrapper");
public static RemoteObject _panel10 = RemoteObject.declareNull("anywheresoftware.b4a.objects.PanelWrapper");
public static RemoteObject _panel11 = RemoteObject.declareNull("anywheresoftware.b4a.objects.PanelWrapper");
public static RemoteObject _panel12 = RemoteObject.declareNull("anywheresoftware.b4a.objects.PanelWrapper");
public static RemoteObject _panel13 = RemoteObject.declareNull("anywheresoftware.b4a.objects.PanelWrapper");
public static RemoteObject _panel14 = RemoteObject.declareNull("anywheresoftware.b4a.objects.PanelWrapper");
public static RemoteObject _panel15 = RemoteObject.declareNull("anywheresoftware.b4a.objects.PanelWrapper");
public static RemoteObject _panel16 = RemoteObject.declareNull("anywheresoftware.b4a.objects.PanelWrapper");
public static RemoteObject _panel17 = RemoteObject.declareNull("anywheresoftware.b4a.objects.PanelWrapper");
public static RemoteObject _panel18 = RemoteObject.declareNull("anywheresoftware.b4a.objects.PanelWrapper");
public static RemoteObject _panel19 = RemoteObject.declareNull("anywheresoftware.b4a.objects.PanelWrapper");
public static RemoteObject _panel20 = RemoteObject.declareNull("anywheresoftware.b4a.objects.PanelWrapper");
public static RemoteObject _panel21 = RemoteObject.declareNull("anywheresoftware.b4a.objects.PanelWrapper");
public static RemoteObject _panel22 = RemoteObject.declareNull("anywheresoftware.b4a.objects.PanelWrapper");
public static RemoteObject _panel23 = RemoteObject.declareNull("anywheresoftware.b4a.objects.PanelWrapper");
public static RemoteObject _panel24 = RemoteObject.declareNull("anywheresoftware.b4a.objects.PanelWrapper");
public static RemoteObject _panel25 = RemoteObject.declareNull("anywheresoftware.b4a.objects.PanelWrapper");
public static RemoteObject _dateutils = RemoteObject.declareNull("b4a.example.dateutils");
public static b4a.example3.main _main = null;
public static b4a.example3.antranorgorussil _antranorgorussil = null;
public static b4a.example3.antranorgoruslistele _antranorgoruslistele = null;
public static b4a.example3.dayanikliliktestlistele _dayanikliliktestlistele = null;
public static b4a.example3.dayanikliliktestsil _dayanikliliktestsil = null;
public static b4a.example3.dayanikliliktestekle _dayanikliliktestekle = null;
public static b4a.example3.gelismistestdenekara _gelismistestdenekara = null;
public static b4a.example3.programayar _programayar = null;
public static b4a.example3.surattestlistele _surattestlistele = null;
public static b4a.example3.deneklistele _deneklistele = null;
public static b4a.example3.dbutils _dbutils = null;
public static b4a.example3.antranorgorusekle _antranorgorusekle = null;
public static b4a.example3.testdenekara _testdenekara = null;
public static b4a.example3.denekekleguncelle _denekekleguncelle = null;
public static b4a.example3.dayanikliliktestmenu _dayanikliliktestmenu = null;
public static b4a.example3.programlistele _programlistele = null;
public static b4a.example3.programsil _programsil = null;
public static b4a.example3.surattestayar _surattestayar = null;
public static b4a.example3.surattestekle _surattestekle = null;
public static b4a.example3.surattestsil _surattestsil = null;
public static b4a.example3.sesservice _sesservice = null;
public static b4a.example3.denekduzenlesil _denekduzenlesil = null;
public static b4a.example3.antropometriklistele _antropometriklistele = null;
public static b4a.example3.saglikbilgilerisil _saglikbilgilerisil = null;
public static b4a.example3.testmenu _testmenu = null;
public static b4a.example3.motorozellikmenu _motorozellikmenu = null;
public static b4a.example3.saglikbilgilerilistele _saglikbilgilerilistele = null;
public static b4a.example3.biyokimyasalekle _biyokimyasalekle = null;
public static b4a.example3.antropometrikekle _antropometrikekle = null;
public static b4a.example3.color _color = null;
public static b4a.example3.anamenu _anamenu = null;
public static b4a.example3.insertveriler _insertveriler = null;
public static b4a.example3.biyokimyasallistele _biyokimyasallistele = null;
public static b4a.example3.biyokimyasalsil _biyokimyasalsil = null;
public static b4a.example3.psikolojiksil _psikolojiksil = null;
public static b4a.example3.psikolojiklistele _psikolojiklistele = null;
public static b4a.example3.antropometriksil _antropometriksil = null;
public static b4a.example3.psikolojikekle _psikolojikekle = null;
public static b4a.example3.starter _starter = null;
public static b4a.example3.saglikbilgileriekle _saglikbilgileriekle = null;
public static b4a.example3.dikeysicramatest _dikeysicramatest = null;
public static b4a.example3.dengetest _dengetest = null;
public static b4a.example3.kuvvettest _kuvvettest = null;
public static b4a.example3.reaksiyontest _reaksiyontest = null;
public static b4a.example3.programsec _programsec = null;
  public Object[] GetGlobals() {
		return new Object[] {"Activity",programveri.mostCurrent._activity,"AnaMenu",Debug.moduleToString(b4a.example3.anamenu.class),"AntranorGorusEkle",Debug.moduleToString(b4a.example3.antranorgorusekle.class),"AntranorGorusListele",Debug.moduleToString(b4a.example3.antranorgoruslistele.class),"AntranorGorusSil",Debug.moduleToString(b4a.example3.antranorgorussil.class),"AntropometrikEkle",Debug.moduleToString(b4a.example3.antropometrikekle.class),"AntropometrikListele",Debug.moduleToString(b4a.example3.antropometriklistele.class),"AntropometrikSil",Debug.moduleToString(b4a.example3.antropometriksil.class),"BiyokimyasalEkle",Debug.moduleToString(b4a.example3.biyokimyasalekle.class),"BiyokimyasalListele",Debug.moduleToString(b4a.example3.biyokimyasallistele.class),"BiyokimyasalSil",Debug.moduleToString(b4a.example3.biyokimyasalsil.class),"ButtonOK",programveri.mostCurrent._buttonok,"Color",Debug.moduleToString(b4a.example3.color.class),"dakika1",programveri._dakika1,"dakika10",programveri._dakika10,"dakika11",programveri._dakika11,"dakika12",programveri._dakika12,"dakika13",programveri._dakika13,"dakika14",programveri._dakika14,"dakika15",programveri._dakika15,"dakika16",programveri._dakika16,"dakika17",programveri._dakika17,"dakika18",programveri._dakika18,"dakika19",programveri._dakika19,"dakika2",programveri._dakika2,"dakika20",programveri._dakika20,"dakika21",programveri._dakika21,"dakika22",programveri._dakika22,"dakika23",programveri._dakika23,"dakika24",programveri._dakika24,"dakika25",programveri._dakika25,"dakika3",programveri._dakika3,"dakika4",programveri._dakika4,"dakika5",programveri._dakika5,"dakika6",programveri._dakika6,"dakika7",programveri._dakika7,"dakika8",programveri._dakika8,"dakika9",programveri._dakika9,"DateUtils",programveri.mostCurrent._dateutils,"DayaniklilikTestEkle",Debug.moduleToString(b4a.example3.dayanikliliktestekle.class),"DayaniklilikTestListele",Debug.moduleToString(b4a.example3.dayanikliliktestlistele.class),"DayaniklilikTestMenu",Debug.moduleToString(b4a.example3.dayanikliliktestmenu.class),"DayaniklilikTestSil",Debug.moduleToString(b4a.example3.dayanikliliktestsil.class),"DBUtils",Debug.moduleToString(b4a.example3.dbutils.class),"DenekDuzenleSil",Debug.moduleToString(b4a.example3.denekduzenlesil.class),"DenekEkleGuncelle",Debug.moduleToString(b4a.example3.denekekleguncelle.class),"DenekListele",Debug.moduleToString(b4a.example3.deneklistele.class),"DengeTest",Debug.moduleToString(b4a.example3.dengetest.class),"DikeySicramaTest",Debug.moduleToString(b4a.example3.dikeysicramatest.class),"EditTextDakika1",programveri.mostCurrent._edittextdakika1,"EditTextDakika10",programveri.mostCurrent._edittextdakika10,"EditTextDakika11",programveri.mostCurrent._edittextdakika11,"EditTextDakika12",programveri.mostCurrent._edittextdakika12,"EditTextDakika13",programveri.mostCurrent._edittextdakika13,"EditTextDakika14",programveri.mostCurrent._edittextdakika14,"EditTextDakika15",programveri.mostCurrent._edittextdakika15,"EditTextDakika16",programveri.mostCurrent._edittextdakika16,"EditTextDakika17",programveri.mostCurrent._edittextdakika17,"EditTextDakika18",programveri.mostCurrent._edittextdakika18,"EditTextDakika19",programveri.mostCurrent._edittextdakika19,"EditTextDakika2",programveri.mostCurrent._edittextdakika2,"EditTextDakika20",programveri.mostCurrent._edittextdakika20,"EditTextDakika21",programveri.mostCurrent._edittextdakika21,"EditTextDakika22",programveri.mostCurrent._edittextdakika22,"EditTextDakika23",programveri.mostCurrent._edittextdakika23,"EditTextDakika24",programveri.mostCurrent._edittextdakika24,"EditTextDakika25",programveri.mostCurrent._edittextdakika25,"EditTextDakika3",programveri.mostCurrent._edittextdakika3,"EditTextDakika4",programveri.mostCurrent._edittextdakika4,"EditTextDakika5",programveri.mostCurrent._edittextdakika5,"EditTextDakika6",programveri.mostCurrent._edittextdakika6,"EditTextDakika7",programveri.mostCurrent._edittextdakika7,"EditTextDakika8",programveri.mostCurrent._edittextdakika8,"EditTextDakika9",programveri.mostCurrent._edittextdakika9,"EditTextHiz1",programveri.mostCurrent._edittexthiz1,"EditTextHiz10",programveri.mostCurrent._edittexthiz10,"EditTextHiz11",programveri.mostCurrent._edittexthiz11,"EditTextHiz12",programveri.mostCurrent._edittexthiz12,"EditTextHiz13",programveri.mostCurrent._edittexthiz13,"EditTextHiz14",programveri.mostCurrent._edittexthiz14,"EditTextHiz15",programveri.mostCurrent._edittexthiz15,"EditTextHiz16",programveri.mostCurrent._edittexthiz16,"EditTextHiz17",programveri.mostCurrent._edittexthiz17,"EditTextHiz18",programveri.mostCurrent._edittexthiz18,"EditTextHiz19",programveri.mostCurrent._edittexthiz19,"EditTextHiz2",programveri.mostCurrent._edittexthiz2,"EditTextHiz20",programveri.mostCurrent._edittexthiz20,"EditTextHiz21",programveri.mostCurrent._edittexthiz21,"EditTextHiz22",programveri.mostCurrent._edittexthiz22,"EditTextHiz23",programveri.mostCurrent._edittexthiz23,"EditTextHiz24",programveri.mostCurrent._edittexthiz24,"EditTextHiz25",programveri.mostCurrent._edittexthiz25,"EditTextHiz3",programveri.mostCurrent._edittexthiz3,"EditTextHiz4",programveri.mostCurrent._edittexthiz4,"EditTextHiz5",programveri.mostCurrent._edittexthiz5,"EditTextHiz6",programveri.mostCurrent._edittexthiz6,"EditTextHiz7",programveri.mostCurrent._edittexthiz7,"EditTextHiz8",programveri.mostCurrent._edittexthiz8,"EditTextHiz9",programveri.mostCurrent._edittexthiz9,"EditTextKoniMesafesi1",programveri.mostCurrent._edittextkonimesafesi1,"EditTextKoniMesafesi10",programveri.mostCurrent._edittextkonimesafesi10,"EditTextKoniMesafesi11",programveri.mostCurrent._edittextkonimesafesi11,"EditTextKoniMesafesi12",programveri.mostCurrent._edittextkonimesafesi12,"EditTextKoniMesafesi13",programveri.mostCurrent._edittextkonimesafesi13,"EditTextKoniMesafesi14",programveri.mostCurrent._edittextkonimesafesi14,"EditTextKoniMesafesi15",programveri.mostCurrent._edittextkonimesafesi15,"EditTextKoniMesafesi16",programveri.mostCurrent._edittextkonimesafesi16,"EditTextKoniMesafesi17",programveri.mostCurrent._edittextkonimesafesi17,"EditTextKoniMesafesi18",programveri.mostCurrent._edittextkonimesafesi18,"EditTextKoniMesafesi19",programveri.mostCurrent._edittextkonimesafesi19,"EditTextKoniMesafesi2",programveri.mostCurrent._edittextkonimesafesi2,"EditTextKoniMesafesi20",programveri.mostCurrent._edittextkonimesafesi20,"EditTextKoniMesafesi21",programveri.mostCurrent._edittextkonimesafesi21,"EditTextKoniMesafesi22",programveri.mostCurrent._edittextkonimesafesi22,"EditTextKoniMesafesi23",programveri.mostCurrent._edittextkonimesafesi23,"EditTextKoniMesafesi24",programveri.mostCurrent._edittextkonimesafesi24,"EditTextKoniMesafesi25",programveri.mostCurrent._edittextkonimesafesi25,"EditTextKoniMesafesi3",programveri.mostCurrent._edittextkonimesafesi3,"EditTextKoniMesafesi4",programveri.mostCurrent._edittextkonimesafesi4,"EditTextKoniMesafesi5",programveri.mostCurrent._edittextkonimesafesi5,"EditTextKoniMesafesi6",programveri.mostCurrent._edittextkonimesafesi6,"EditTextKoniMesafesi7",programveri.mostCurrent._edittextkonimesafesi7,"EditTextKoniMesafesi8",programveri.mostCurrent._edittextkonimesafesi8,"EditTextKoniMesafesi9",programveri.mostCurrent._edittextkonimesafesi9,"EditTextSaniye1",programveri.mostCurrent._edittextsaniye1,"EditTextSaniye10",programveri.mostCurrent._edittextsaniye10,"EditTextSaniye11",programveri.mostCurrent._edittextsaniye11,"EditTextSaniye12",programveri.mostCurrent._edittextsaniye12,"EditTextSaniye13",programveri.mostCurrent._edittextsaniye13,"EditTextSaniye14",programveri.mostCurrent._edittextsaniye14,"EditTextSaniye15",programveri.mostCurrent._edittextsaniye15,"EditTextSaniye16",programveri.mostCurrent._edittextsaniye16,"EditTextSaniye17",programveri.mostCurrent._edittextsaniye17,"EditTextSaniye18",programveri.mostCurrent._edittextsaniye18,"EditTextSaniye19",programveri.mostCurrent._edittextsaniye19,"EditTextSaniye2",programveri.mostCurrent._edittextsaniye2,"EditTextSaniye20",programveri.mostCurrent._edittextsaniye20,"EditTextSaniye21",programveri.mostCurrent._edittextsaniye21,"EditTextSaniye22",programveri.mostCurrent._edittextsaniye22,"EditTextSaniye23",programveri.mostCurrent._edittextsaniye23,"EditTextSaniye24",programveri.mostCurrent._edittextsaniye24,"EditTextSaniye25",programveri.mostCurrent._edittextsaniye25,"EditTextSaniye3",programveri.mostCurrent._edittextsaniye3,"EditTextSaniye4",programveri.mostCurrent._edittextsaniye4,"EditTextSaniye5",programveri.mostCurrent._edittextsaniye5,"EditTextSaniye6",programveri.mostCurrent._edittextsaniye6,"EditTextSaniye7",programveri.mostCurrent._edittextsaniye7,"EditTextSaniye8",programveri.mostCurrent._edittextsaniye8,"EditTextSaniye9",programveri.mostCurrent._edittextsaniye9,"GelismisTestDenekAra",Debug.moduleToString(b4a.example3.gelismistestdenekara.class),"hiz1",programveri._hiz1,"hiz10",programveri._hiz10,"hiz11",programveri._hiz11,"hiz12",programveri._hiz12,"hiz13",programveri._hiz13,"hiz14",programveri._hiz14,"hiz15",programveri._hiz15,"hiz16",programveri._hiz16,"hiz17",programveri._hiz17,"hiz18",programveri._hiz18,"hiz19",programveri._hiz19,"hiz2",programveri._hiz2,"hiz20",programveri._hiz20,"hiz21",programveri._hiz21,"hiz22",programveri._hiz22,"hiz23",programveri._hiz23,"hiz24",programveri._hiz24,"hiz25",programveri._hiz25,"hiz3",programveri._hiz3,"hiz4",programveri._hiz4,"hiz5",programveri._hiz5,"hiz6",programveri._hiz6,"hiz7",programveri._hiz7,"hiz8",programveri._hiz8,"hiz9",programveri._hiz9,"InsertVeriler",Debug.moduleToString(b4a.example3.insertveriler.class),"koniMesafesi1",programveri._konimesafesi1,"koniMesafesi10",programveri._konimesafesi10,"koniMesafesi11",programveri._konimesafesi11,"koniMesafesi12",programveri._konimesafesi12,"koniMesafesi13",programveri._konimesafesi13,"koniMesafesi14",programveri._konimesafesi14,"koniMesafesi15",programveri._konimesafesi15,"koniMesafesi16",programveri._konimesafesi16,"koniMesafesi17",programveri._konimesafesi17,"koniMesafesi18",programveri._konimesafesi18,"koniMesafesi19",programveri._konimesafesi19,"koniMesafesi2",programveri._konimesafesi2,"koniMesafesi20",programveri._konimesafesi20,"koniMesafesi21",programveri._konimesafesi21,"koniMesafesi22",programveri._konimesafesi22,"koniMesafesi23",programveri._konimesafesi23,"koniMesafesi24",programveri._konimesafesi24,"koniMesafesi25",programveri._konimesafesi25,"koniMesafesi3",programveri._konimesafesi3,"koniMesafesi4",programveri._konimesafesi4,"koniMesafesi5",programveri._konimesafesi5,"koniMesafesi6",programveri._konimesafesi6,"koniMesafesi7",programveri._konimesafesi7,"koniMesafesi8",programveri._konimesafesi8,"koniMesafesi9",programveri._konimesafesi9,"KuvvetTest",Debug.moduleToString(b4a.example3.kuvvettest.class),"LabelDakika1",programveri.mostCurrent._labeldakika1,"LabelDakika10",programveri.mostCurrent._labeldakika10,"LabelDakika11",programveri.mostCurrent._labeldakika11,"LabelDakika12",programveri.mostCurrent._labeldakika12,"LabelDakika13",programveri.mostCurrent._labeldakika13,"LabelDakika14",programveri.mostCurrent._labeldakika14,"LabelDakika15",programveri.mostCurrent._labeldakika15,"LabelDakika16",programveri.mostCurrent._labeldakika16,"LabelDakika17",programveri.mostCurrent._labeldakika17,"LabelDakika18",programveri.mostCurrent._labeldakika18,"LabelDakika19",programveri.mostCurrent._labeldakika19,"LabelDakika2",programveri.mostCurrent._labeldakika2,"LabelDakika20",programveri.mostCurrent._labeldakika20,"LabelDakika21",programveri.mostCurrent._labeldakika21,"LabelDakika22",programveri.mostCurrent._labeldakika22,"LabelDakika23",programveri.mostCurrent._labeldakika23,"LabelDakika24",programveri.mostCurrent._labeldakika24,"LabelDakika25",programveri.mostCurrent._labeldakika25,"LabelDakika3",programveri.mostCurrent._labeldakika3,"LabelDakika4",programveri.mostCurrent._labeldakika4,"LabelDakika5",programveri.mostCurrent._labeldakika5,"LabelDakika6",programveri.mostCurrent._labeldakika6,"LabelDakika7",programveri.mostCurrent._labeldakika7,"LabelDakika8",programveri.mostCurrent._labeldakika8,"LabelDakika9",programveri.mostCurrent._labeldakika9,"LabelHiz1",programveri.mostCurrent._labelhiz1,"LabelHiz10",programveri.mostCurrent._labelhiz10,"LabelHiz11",programveri.mostCurrent._labelhiz11,"LabelHiz12",programveri.mostCurrent._labelhiz12,"LabelHiz13",programveri.mostCurrent._labelhiz13,"LabelHiz14",programveri.mostCurrent._labelhiz14,"LabelHiz15",programveri.mostCurrent._labelhiz15,"LabelHiz16",programveri.mostCurrent._labelhiz16,"LabelHiz17",programveri.mostCurrent._labelhiz17,"LabelHiz18",programveri.mostCurrent._labelhiz18,"LabelHiz19",programveri.mostCurrent._labelhiz19,"LabelHiz2",programveri.mostCurrent._labelhiz2,"LabelHiz20",programveri.mostCurrent._labelhiz20,"LabelHiz21",programveri.mostCurrent._labelhiz21,"LabelHiz22",programveri.mostCurrent._labelhiz22,"LabelHiz23",programveri.mostCurrent._labelhiz23,"LabelHiz24",programveri.mostCurrent._labelhiz24,"LabelHiz25",programveri.mostCurrent._labelhiz25,"LabelHiz3",programveri.mostCurrent._labelhiz3,"LabelHiz4",programveri.mostCurrent._labelhiz4,"LabelHiz5",programveri.mostCurrent._labelhiz5,"LabelHiz6",programveri.mostCurrent._labelhiz6,"LabelHiz7",programveri.mostCurrent._labelhiz7,"LabelHiz8",programveri.mostCurrent._labelhiz8,"LabelHiz9",programveri.mostCurrent._labelhiz9,"LabelKoniMesafesi1",programveri.mostCurrent._labelkonimesafesi1,"LabelKoniMesafesi10",programveri.mostCurrent._labelkonimesafesi10,"LabelKoniMesafesi11",programveri.mostCurrent._labelkonimesafesi11,"LabelKoniMesafesi12",programveri.mostCurrent._labelkonimesafesi12,"LabelKoniMesafesi13",programveri.mostCurrent._labelkonimesafesi13,"LabelKoniMesafesi14",programveri.mostCurrent._labelkonimesafesi14,"LabelKoniMesafesi15",programveri.mostCurrent._labelkonimesafesi15,"LabelKoniMesafesi16",programveri.mostCurrent._labelkonimesafesi16,"LabelKoniMesafesi17",programveri.mostCurrent._labelkonimesafesi17,"LabelKoniMesafesi18",programveri.mostCurrent._labelkonimesafesi18,"LabelKoniMesafesi19",programveri.mostCurrent._labelkonimesafesi19,"LabelKoniMesafesi2",programveri.mostCurrent._labelkonimesafesi2,"LabelKoniMesafesi20",programveri.mostCurrent._labelkonimesafesi20,"LabelKoniMesafesi21",programveri.mostCurrent._labelkonimesafesi21,"LabelKoniMesafesi22",programveri.mostCurrent._labelkonimesafesi22,"LabelKoniMesafesi23",programveri.mostCurrent._labelkonimesafesi23,"LabelKoniMesafesi24",programveri.mostCurrent._labelkonimesafesi24,"LabelKoniMesafesi25",programveri.mostCurrent._labelkonimesafesi25,"LabelKoniMesafesi3",programveri.mostCurrent._labelkonimesafesi3,"LabelKoniMesafesi4",programveri.mostCurrent._labelkonimesafesi4,"LabelKoniMesafesi5",programveri.mostCurrent._labelkonimesafesi5,"LabelKoniMesafesi6",programveri.mostCurrent._labelkonimesafesi6,"LabelKoniMesafesi7",programveri.mostCurrent._labelkonimesafesi7,"LabelKoniMesafesi8",programveri.mostCurrent._labelkonimesafesi8,"LabelKoniMesafesi9",programveri.mostCurrent._labelkonimesafesi9,"LabelSaniye1",programveri.mostCurrent._labelsaniye1,"LabelSaniye10",programveri.mostCurrent._labelsaniye10,"LabelSaniye11",programveri.mostCurrent._labelsaniye11,"LabelSaniye12",programveri.mostCurrent._labelsaniye12,"LabelSaniye13",programveri.mostCurrent._labelsaniye13,"LabelSaniye14",programveri.mostCurrent._labelsaniye14,"LabelSaniye15",programveri.mostCurrent._labelsaniye15,"LabelSaniye16",programveri.mostCurrent._labelsaniye16,"LabelSaniye17",programveri.mostCurrent._labelsaniye17,"LabelSaniye18",programveri.mostCurrent._labelsaniye18,"LabelSaniye19",programveri.mostCurrent._labelsaniye19,"LabelSaniye2",programveri.mostCurrent._labelsaniye2,"LabelSaniye20",programveri.mostCurrent._labelsaniye20,"LabelSaniye21",programveri.mostCurrent._labelsaniye21,"LabelSaniye22",programveri.mostCurrent._labelsaniye22,"LabelSaniye23",programveri.mostCurrent._labelsaniye23,"LabelSaniye24",programveri.mostCurrent._labelsaniye24,"LabelSaniye25",programveri.mostCurrent._labelsaniye25,"LabelSaniye3",programveri.mostCurrent._labelsaniye3,"LabelSaniye4",programveri.mostCurrent._labelsaniye4,"LabelSaniye5",programveri.mostCurrent._labelsaniye5,"LabelSaniye6",programveri.mostCurrent._labelsaniye6,"LabelSaniye7",programveri.mostCurrent._labelsaniye7,"LabelSaniye8",programveri.mostCurrent._labelsaniye8,"LabelSaniye9",programveri.mostCurrent._labelsaniye9,"LabelSeviyeIsmi1",programveri.mostCurrent._labelseviyeismi1,"LabelSeviyeIsmi10",programveri.mostCurrent._labelseviyeismi10,"LabelSeviyeIsmi11",programveri.mostCurrent._labelseviyeismi11,"LabelSeviyeIsmi12",programveri.mostCurrent._labelseviyeismi12,"LabelSeviyeIsmi13",programveri.mostCurrent._labelseviyeismi13,"LabelSeviyeIsmi14",programveri.mostCurrent._labelseviyeismi14,"LabelSeviyeIsmi15",programveri.mostCurrent._labelseviyeismi15,"LabelSeviyeIsmi16",programveri.mostCurrent._labelseviyeismi16,"LabelSeviyeIsmi17",programveri.mostCurrent._labelseviyeismi17,"LabelSeviyeIsmi18",programveri.mostCurrent._labelseviyeismi18,"LabelSeviyeIsmi19",programveri.mostCurrent._labelseviyeismi19,"LabelSeviyeIsmi2",programveri.mostCurrent._labelseviyeismi2,"LabelSeviyeIsmi20",programveri.mostCurrent._labelseviyeismi20,"LabelSeviyeIsmi21",programveri.mostCurrent._labelseviyeismi21,"LabelSeviyeIsmi22",programveri.mostCurrent._labelseviyeismi22,"LabelSeviyeIsmi23",programveri.mostCurrent._labelseviyeismi23,"LabelSeviyeIsmi24",programveri.mostCurrent._labelseviyeismi24,"LabelSeviyeIsmi25",programveri.mostCurrent._labelseviyeismi25,"LabelSeviyeIsmi3",programveri.mostCurrent._labelseviyeismi3,"LabelSeviyeIsmi4",programveri.mostCurrent._labelseviyeismi4,"LabelSeviyeIsmi5",programveri.mostCurrent._labelseviyeismi5,"LabelSeviyeIsmi6",programveri.mostCurrent._labelseviyeismi6,"LabelSeviyeIsmi7",programveri.mostCurrent._labelseviyeismi7,"LabelSeviyeIsmi8",programveri.mostCurrent._labelseviyeismi8,"LabelSeviyeIsmi9",programveri.mostCurrent._labelseviyeismi9,"Main",Debug.moduleToString(b4a.example3.main.class),"MotorOzellikMenu",Debug.moduleToString(b4a.example3.motorozellikmenu.class),"Panel1",programveri.mostCurrent._panel1,"Panel10",programveri.mostCurrent._panel10,"Panel11",programveri.mostCurrent._panel11,"Panel12",programveri.mostCurrent._panel12,"Panel13",programveri.mostCurrent._panel13,"Panel14",programveri.mostCurrent._panel14,"Panel15",programveri.mostCurrent._panel15,"Panel16",programveri.mostCurrent._panel16,"Panel17",programveri.mostCurrent._panel17,"Panel18",programveri.mostCurrent._panel18,"Panel19",programveri.mostCurrent._panel19,"Panel2",programveri.mostCurrent._panel2,"Panel20",programveri.mostCurrent._panel20,"Panel21",programveri.mostCurrent._panel21,"Panel22",programveri.mostCurrent._panel22,"Panel23",programveri.mostCurrent._panel23,"Panel24",programveri.mostCurrent._panel24,"Panel25",programveri.mostCurrent._panel25,"Panel3",programveri.mostCurrent._panel3,"Panel4",programveri.mostCurrent._panel4,"Panel5",programveri.mostCurrent._panel5,"Panel6",programveri.mostCurrent._panel6,"Panel7",programveri.mostCurrent._panel7,"Panel8",programveri.mostCurrent._panel8,"Panel9",programveri.mostCurrent._panel9,"ProgramAyar",Debug.moduleToString(b4a.example3.programayar.class),"ProgramID",programveri._programid,"ProgramListele",Debug.moduleToString(b4a.example3.programlistele.class),"ProgramSec",Debug.moduleToString(b4a.example3.programsec.class),"ProgramSil",Debug.moduleToString(b4a.example3.programsil.class),"PsikolojikEkle",Debug.moduleToString(b4a.example3.psikolojikekle.class),"PsikolojikListele",Debug.moduleToString(b4a.example3.psikolojiklistele.class),"PsikolojikSil",Debug.moduleToString(b4a.example3.psikolojiksil.class),"ReaksiyonTest",Debug.moduleToString(b4a.example3.reaksiyontest.class),"rs",programveri.mostCurrent._rs,"SaglikBilgileriEkle",Debug.moduleToString(b4a.example3.saglikbilgileriekle.class),"SaglikBilgileriListele",Debug.moduleToString(b4a.example3.saglikbilgilerilistele.class),"SaglikBilgileriSil",Debug.moduleToString(b4a.example3.saglikbilgilerisil.class),"saniye1",programveri._saniye1,"saniye10",programveri._saniye10,"saniye11",programveri._saniye11,"saniye12",programveri._saniye12,"saniye13",programveri._saniye13,"saniye14",programveri._saniye14,"saniye15",programveri._saniye15,"saniye16",programveri._saniye16,"saniye17",programveri._saniye17,"saniye18",programveri._saniye18,"saniye19",programveri._saniye19,"saniye2",programveri._saniye2,"saniye20",programveri._saniye20,"saniye21",programveri._saniye21,"saniye22",programveri._saniye22,"saniye23",programveri._saniye23,"saniye24",programveri._saniye24,"saniye25",programveri._saniye25,"saniye3",programveri._saniye3,"saniye4",programveri._saniye4,"saniye5",programveri._saniye5,"saniye6",programveri._saniye6,"saniye7",programveri._saniye7,"saniye8",programveri._saniye8,"saniye9",programveri._saniye9,"ScrollView1",programveri.mostCurrent._scrollview1,"secilenSaat",programveri.mostCurrent._secilensaat,"secilenTarih",programveri.mostCurrent._secilentarih,"SesService",Debug.moduleToString(b4a.example3.sesservice.class),"Starter",Debug.moduleToString(b4a.example3.starter.class),"SuratTestAyar",Debug.moduleToString(b4a.example3.surattestayar.class),"SuratTestEkle",Debug.moduleToString(b4a.example3.surattestekle.class),"SuratTestListele",Debug.moduleToString(b4a.example3.surattestlistele.class),"SuratTestSil",Debug.moduleToString(b4a.example3.surattestsil.class),"TestDenekAra",Debug.moduleToString(b4a.example3.testdenekara.class),"TestMenu",Debug.moduleToString(b4a.example3.testmenu.class)};
}
}